### ISSUE TITLE
Continuing Kartini's

### ISSUE THREAD

**Issue by frederett** [artileda/artileda#2]
Dear, Artileda.

Thank for creating it, I had interest to continue [kartini](https://github.com/artileda/kartini), because I recently get interested with package manager concept. It's a shame, if it's left unattended.

My plan with this project is adding some feature improvement such adding versioning, package exception, and  refactoring. since it hadn't good unit test.

Thank you.

**Comment by artileda** [comment]
Thank you for put attention to kartini. I'll transfer repo it soon, I just want my name not removed as a credits and of course you can add your name next after mine.

The reason I left it behind because dumb decision I made, such not accept external dependencies like using ocaml git library instead spawn git from system and lack of management both time and feature. 

The most important feature is dependencies resolving capabilities that left missing because my ignorant, like SAT or something. I just use basic loop to resolve dependencies.

And again, thank you for adopting my code :')
